name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        ls -l
        cd app
        node -v
        npm -v
        npm install --slient
        ng build --prod --output-path docs --base-href /adsm-demo/
        
